name: EmojiPlugin
version: '${version}'
main: net.lumamc.nexo.EmojiPlugin
api-version: '1.21'
author: Mitality
description: LumaMC Nexo-based Emoji Plugin
folia-supported: true
depend:
  - Nexo
softdepend:
  - LuckPerms
  - ProtocolLib
